openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact Book API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    Це API для керування контактами з авторизацією, поштою та аватарками.
tags:
  - name: auth
    description: Авторизація
  - name: contacts
    description: Операції з контактами
  - name: users
    description: Операції з користувачем
servers:
  - url: http://localhost:3000
  - url: https://https://nodejs-hw-mongodb-lilya.onrender.com
paths:
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'

  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/{contactId}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{contactId}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{contactId}/delete.yaml'

  /users/register:
    post:
      $ref: '../swagger/paths/users/register.yaml'

  /users/login:
    post:
      $ref: '../swagger/paths/users/login.yaml'

  /users/logout:
    post:
      $ref: '../swagger/paths/users/logout.yaml'

  /users/current:
    get:
      $ref: '../swagger/paths/users/current.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
